items:
- stem: CWE78_OS_Command_Injection__char_connect_socket_execl_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1075576832
  region_size: 16384
- stem: CWE78_OS_Command_Injection__char_console_popen_01
  io: STDIN
  segment: DATA
  effect: EXEC
  addr_class: FIXED
  fixed_base: 1075642368
  region_size: 16384
- stem: CWE78_OS_Command_Injection__char_environment_w32_execv_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1075707904
  region_size: 16384
- stem: CWE114_Process_Control__w32_char_connect_socket_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1073741824
  region_size: 16384
- stem: CWE114_Process_Control__w32_char_console_02
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1073807360
  region_size: 16384
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE129_fgets_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1073938432
  region_size: 8192
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE129_fscanf_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1074003968
  region_size: 8192
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE805_char_declare_memcpy_01
  io: STDIN
  segment: STACK
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1610612736
  region_size: 8192
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE805_int64_t_declare_memmove_01
  io: STDIN
  segment: STACK
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1610678272
  region_size: 8192
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_cpy_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1074069504
  region_size: 8192
- stem: CWE122_Heap_Based_Buffer_Overflow__c_CWE805_char_memcpy_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1342177280
  region_size: 8192
- stem: CWE122_Heap_Based_Buffer_Overflow__c_CWE805_wchar_t_memmove_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1342242816
  region_size: 8192
- stem: CWE124_Buffer_Underwrite__char_declare_memmove_01
  io: STDIN
  segment: STACK
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1610743808
  region_size: 8192
- stem: CWE124_Buffer_Underwrite__malloc_char_memmove_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1342308352
  region_size: 8192
- stem: CWE126_Buffer_Overread__malloc_char_memcpy_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1342373888
  region_size: 8192
- stem: CWE126_Buffer_Overread__char_declare_memcpy_01
  io: STDIN
  segment: STACK
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1610809344
  region_size: 8192
- stem: CWE127_Buffer_Underread__char_declare_memmove_01
  io: STDIN
  segment: STACK
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1610874880
  region_size: 8192
- stem: CWE127_Buffer_Underread__malloc_char_memcpy_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1342439424
  region_size: 8192
- stem: CWE190_Integer_Overflow__int_max_add_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
  addr_class: FIXED
  fixed_base: 1074200576
  region_size: 4096
- stem: CWE190_Integer_Overflow__int_fscanf_multiply_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
  addr_class: FIXED
  fixed_base: 1074135040
  region_size: 4096
- stem: CWE191_Integer_Underflow__int_fscanf_sub_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
  addr_class: FIXED
  fixed_base: 1074266112
  region_size: 4096
- stem: CWE191_Integer_Underflow__int_min_sub_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
  addr_class: FIXED
  fixed_base: 1074331648
  region_size: 4096
- stem: CWE194_Unexpected_Sign_Extension__negative_memcpy_01
  io: STDIN
  segment: STACK
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1610940416
  region_size: 4096
- stem: CWE197_Numeric_Truncation_Error__int_fscanf_to_short_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
  addr_class: FIXED
  fixed_base: 1074397184
  region_size: 4096
- stem: CWE226_Sensitive_Information_Uncleared_Before_Release__w32_char_alloca_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1074462720
  region_size: 4096
- stem: CWE226_Sensitive_Information_Uncleared_Before_Release__w32_char_declare_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1074528256
  region_size: 4096
- stem: CWE226_Sensitive_Information_Uncleared_Before_Release__w32_wchar_t_alloca_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1074593792
  region_size: 4096
- stem: CWE535_Info_Exposure_Shell_Error__w32_char_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1075314688
  region_size: 4096
- stem: CWE535_Info_Exposure_Shell_Error__w32_wchar_t_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1075380224
  region_size: 4096
- stem: CWE562_Return_of_Stack_Variable_Address__return_buf_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1075445760
  region_size: 4096
- stem: CWE587_Assignment_of_Fixed_Address_to_Pointer__basic_01
  io: STDIN
  segment: DATA
  effect: READ
  addr_class: FIXED
  fixed_base: 1075511296
  region_size: 4096
- stem: CWE78_OS_Command_Injection__char_listen_socket_system_01
  io: STDIN
  segment: DATA
  effect: EXEC
  addr_class: FIXED
  fixed_base: 1075773440
  region_size: 16384
- stem: CWE114_Process_Control__w32_char_environment_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1073872896
  region_size: 16384
- stem: CWE272_Least_Privilege_Violation__w32_char_CreateProcessAsUser_01
  io: STDIN
  segment: DATA
  effect: READ
  addr_class: FIXED
  fixed_base: 1074659328
  region_size: 16384
- stem: CWE273_Improper_Check_for_Dropped_Privileges__w32_ImpersonateNamedPipeClient_01
  io: STDIN
  segment: DATA
  effect: READ
  addr_class: FIXED
  fixed_base: 1074724864
  region_size: 16384
- stem: CWE321_Hard_Coded_Cryptographic_Key__w32_char_01
  io: STDIN
  segment: STACK
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1611005952
  region_size: 16384
- stem: CWE321_Hard_Coded_Cryptographic_Key__w32_wchar_t_01
  io: STDIN
  segment: STACK
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1611071488
  region_size: 16384
- stem: CWE364_Signal_Handler_Race_Condition__basic_01
  io: STDIN
  segment: HEAP
  effect: READ
  addr_class: FIXED
  fixed_base: 1342504960
  region_size: 4096
- stem: CWE367_TOC_TOU__access_01
  io: STDIN
  segment: DATA
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1074790400
  region_size: 4096
- stem: CWE369_Divide_by_Zero__int_rand_divide_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
  addr_class: FIXED
  fixed_base: 1074855936
  region_size: 4096
- stem: CWE401_Memory_Leak__char_calloc_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1342570496
  region_size: 8192
- stem: CWE401_Memory_Leak__char_malloc_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1342636032
  region_size: 8192
- stem: CWE401_Memory_Leak__char_realloc_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1342701568
  region_size: 8192
- stem: CWE401_Memory_Leak__int64_t_calloc_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1342767104
  region_size: 8192
- stem: CWE401_Memory_Leak__strdup_wchar_t_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1342832640
  region_size: 8192
- stem: CWE401_Memory_Leak__struct_twoIntsStruct_calloc_01
  io: STDIN
  segment: HEAP
  effect: READ
  addr_class: FIXED
  fixed_base: 1342898176
  region_size: 8192
- stem: CWE415_Double_Free__malloc_free_char_01
  io: STDIN
  segment: HEAP
  effect: READ
  addr_class: FIXED
  fixed_base: 1342963712
  region_size: 8192
- stem: CWE415_Double_Free__malloc_free_int64_t_01
  io: STDIN
  segment: HEAP
  effect: READ
  addr_class: FIXED
  fixed_base: 1343029248
  region_size: 8192
- stem: CWE415_Double_Free__malloc_free_int_01
  io: STDIN
  segment: HEAP
  effect: READ
  addr_class: FIXED
  fixed_base: 1343094784
  region_size: 8192
- stem: CWE415_Double_Free__malloc_free_long_01
  io: STDIN
  segment: HEAP
  effect: READ
  addr_class: FIXED
  fixed_base: 1343160320
  region_size: 8192
- stem: CWE415_Double_Free__malloc_free_struct_01
  io: STDIN
  segment: HEAP
  effect: READ
  addr_class: FIXED
  fixed_base: 1343225856
  region_size: 8192
- stem: CWE415_Double_Free__malloc_free_wchar_t_01
  io: STDIN
  segment: HEAP
  effect: READ
  addr_class: FIXED
  fixed_base: 1343291392
  region_size: 8192
- stem: CWE416_Use_After_Free__malloc_free_char_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1343356928
  region_size: 8192
- stem: CWE416_Use_After_Free__malloc_free_int_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1343422464
  region_size: 8192
- stem: CWE416_Use_After_Free__malloc_free_long_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1343488000
  region_size: 8192
- stem: CWE416_Use_After_Free__malloc_free_struct_10
  io: STDIN
  segment: HEAP
  effect: READ
  addr_class: FIXED
  fixed_base: 1343553536
  region_size: 8192
- stem: CWE416_Use_After_Free__return_freed_ptr_01
  io: STDIN
  segment: HEAP
  effect: WRITE
  addr_class: FIXED
  fixed_base: 1343619072
  region_size: 8192
- stem: CWE457_Use_of_Uninitialized_Variable__int_01
  io: STDIN
  segment: DATA
  effect: READ
  addr_class: FIXED
  fixed_base: 1074921472
  region_size: 4096
- stem: CWE467_Use_of_sizeof_on_Pointer_Type__char_01
  io: STDIN
  segment: HEAP
  effect: READ
  addr_class: FIXED
  fixed_base: 1343684608
  region_size: 4096
- stem: CWE476_NULL_Pointer_Dereference__struct_01
  io: STDIN
  segment: DATA
  effect: READ
  addr_class: FIXED
  fixed_base: 1074987008
  region_size: 4096
- stem: CWE478_Missing_Default_Case_in_Switch__basic_01
  io: STDIN
  segment: DATA
  effect: READ
  addr_class: FIXED
  fixed_base: 1075052544
  region_size: 4096
- stem: CWE481_Assigning_Instead_of_Comparing__basic_01
  io: STDIN
  segment: DATA
  effect: READ
  addr_class: FIXED
  fixed_base: 1075118080
  region_size: 4096
- stem: CWE484_Omitted_Break_Statement_in_Switch__basic_01
  io: STDIN
  segment: DATA
  effect: READ
  addr_class: FIXED
  fixed_base: 1075183616
  region_size: 4096
- stem: CWE526_Info_Exposure_Environment_Variables__basic_01
  io: ENV
  segment: DATA
  effect: READ
  addr_class: FIXED
  fixed_base: 1075249152
  region_size: 4096
