items:
- stem: CWE78_OS_Command_Injection__char_connect_socket_execl_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE78_OS_Command_Injection__char_console_popen_01
  io: STDIN
  segment: DATA
  effect: EXEC
- stem: CWE78_OS_Command_Injection__char_environment_w32_execv_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE114_Process_Control__w32_char_connect_socket_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE114_Process_Control__w32_char_console_02
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE129_fgets_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE129_fscanf_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE805_char_declare_memcpy_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE805_int64_t_declare_memmove_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_cpy_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE122_Heap_Based_Buffer_Overflow__c_CWE805_char_memcpy_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE122_Heap_Based_Buffer_Overflow__c_CWE805_wchar_t_memmove_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE124_Buffer_Underwrite__char_declare_memmove_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE124_Buffer_Underwrite__malloc_char_memmove_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE126_Buffer_Overread__malloc_char_memcpy_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE126_Buffer_Overread__char_declare_memcpy_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE127_Buffer_Underread__char_declare_memmove_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE127_Buffer_Underread__malloc_char_memcpy_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE190_Integer_Overflow__int_max_add_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
- stem: CWE190_Integer_Overflow__int_fscanf_multiply_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
- stem: CWE191_Integer_Underflow__int_fscanf_sub_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
- stem: CWE191_Integer_Underflow__int_min_sub_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
- stem: CWE194_Unexpected_Sign_Extension__negative_memcpy_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE197_Numeric_Truncation_Error__int_fscanf_to_short_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
- stem: CWE226_Sensitive_Information_Uncleared_Before_Release__w32_char_alloca_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE226_Sensitive_Information_Uncleared_Before_Release__w32_char_declare_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE226_Sensitive_Information_Uncleared_Before_Release__w32_wchar_t_alloca_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE535_Info_Exposure_Shell_Error__w32_char_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE535_Info_Exposure_Shell_Error__w32_wchar_t_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE562_Return_of_Stack_Variable_Address__return_buf_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE587_Assignment_of_Fixed_Address_to_Pointer__basic_01
  io: STDIN
  segment: DATA
  effect: READ
- stem: CWE78_OS_Command_Injection__char_listen_socket_system_01
  io: STDIN
  segment: DATA
  effect: EXEC
- stem: CWE114_Process_Control__w32_char_environment_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE272_Least_Privilege_Violation__w32_char_CreateProcessAsUser_01
  io: STDIN
  segment: DATA
  effect: READ
- stem: CWE273_Improper_Check_for_Dropped_Privileges__w32_ImpersonateNamedPipeClient_01
  io: STDIN
  segment: DATA
  effect: READ
- stem: CWE321_Hard_Coded_Cryptographic_Key__w32_char_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE321_Hard_Coded_Cryptographic_Key__w32_wchar_t_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE364_Signal_Handler_Race_Condition__basic_01
  io: STDIN
  segment: HEAP
  effect: READ
- stem: CWE367_TOC_TOU__access_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE369_Divide_by_Zero__int_rand_divide_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
- stem: CWE401_Memory_Leak__char_calloc_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE401_Memory_Leak__char_malloc_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE401_Memory_Leak__char_realloc_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE401_Memory_Leak__int64_t_calloc_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE401_Memory_Leak__strdup_wchar_t_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE401_Memory_Leak__struct_twoIntsStruct_calloc_01
  io: STDIN
  segment: HEAP
  effect: READ
- stem: CWE415_Double_Free__malloc_free_char_01
  io: STDIN
  segment: HEAP
  effect: READ
- stem: CWE415_Double_Free__malloc_free_int64_t_01
  io: STDIN
  segment: HEAP
  effect: READ
- stem: CWE415_Double_Free__malloc_free_int_01
  io: STDIN
  segment: HEAP
  effect: READ
- stem: CWE415_Double_Free__malloc_free_long_01
  io: STDIN
  segment: HEAP
  effect: READ
- stem: CWE415_Double_Free__malloc_free_struct_01
  io: STDIN
  segment: HEAP
  effect: READ
- stem: CWE415_Double_Free__malloc_free_wchar_t_01
  io: STDIN
  segment: HEAP
  effect: READ
- stem: CWE416_Use_After_Free__malloc_free_char_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE416_Use_After_Free__malloc_free_int_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE416_Use_After_Free__malloc_free_long_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE416_Use_After_Free__malloc_free_struct_10
  io: STDIN
  segment: HEAP
  effect: READ
- stem: CWE416_Use_After_Free__return_freed_ptr_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE457_Use_of_Uninitialized_Variable__int_01
  io: STDIN
  segment: DATA
  effect: READ
- stem: CWE467_Use_of_sizeof_on_Pointer_Type__char_01
  io: STDIN
  segment: HEAP
  effect: READ
- stem: CWE476_NULL_Pointer_Dereference__struct_01
  io: STDIN
  segment: DATA
  effect: READ
- stem: CWE478_Missing_Default_Case_in_Switch__basic_01
  io: STDIN
  segment: DATA
  effect: READ
- stem: CWE481_Assigning_Instead_of_Comparing__basic_01
  io: STDIN
  segment: DATA
  effect: READ
- stem: CWE484_Omitted_Break_Statement_in_Switch__basic_01
  io: STDIN
  segment: DATA
  effect: READ
- stem: CWE526_Info_Exposure_Environment_Variables__basic_01
  io: ENV
  segment: DATA
  effect: READ
