items:
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE129_fgets_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE129_fscanf_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE805_char_declare_memcpy_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE805_int64_t_declare_memmove_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_cpy_01
  io: STDIN
  segment: DATA
  effect: WRITE
- stem: CWE122_Heap_Based_Buffer_Overflow__c_CWE805_char_memcpy_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE122_Heap_Based_Buffer_Overflow__c_CWE805_wchar_t_memmove_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE124_Buffer_Underwrite__char_declare_memmove_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE124_Buffer_Underwrite__malloc_char_memmove_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE126_Buffer_Overread__malloc_char_memcpy_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE126_Buffer_Overread__char_declare_memcpy_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE127_Buffer_Underread__char_declare_memmove_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE127_Buffer_Underread__malloc_char_memcpy_01
  io: STDIN
  segment: HEAP
  effect: WRITE
- stem: CWE190_Integer_Overflow__int_max_add_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
- stem: CWE190_Integer_Overflow__int_fscanf_multiply_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
- stem: CWE191_Integer_Underflow__int_fscanf_sub_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
- stem: CWE191_Integer_Underflow__int_min_sub_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
- stem: CWE194_Unexpected_Sign_Extension__negative_memcpy_01
  io: STDIN
  segment: STACK
  effect: WRITE
- stem: CWE197_Numeric_Truncation_Error__int_fscanf_to_short_01
  io: STDIN
  segment: DATA
  effect: TRIGGER
